const mockProducts = [
  {
    id: 1,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 1",
    description: "Description 1",
    isNew: false,
    price: 29.99,
  },
  {
    id: 2,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 2",
    description: "Description 2",
    isNew: false,
    price: 49.99,
    discountPrice: 39.99,
  },
  {
    id: 3,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 3",
    description: "Description 3",
    price: 19.99,
    isNew: true,
  },
  {
    id: 4,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 4",
    description: "Description 4",
    price: 89.99,
    discountPrice: 79.99,
  },
  {
    id: 5,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 1",
    description: "Description 1",
    price: 29.99,
  },
  {
    id: 6,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 2",
    description: "Description 2",
    price: 49.99,
    discountPrice: 39.99,
  },
  {
    id: 7,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 3",
    description: "Description 3",
    price: 19.99,
  },
  {
    id: 8,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 4",
    description: "Description 4",
    price: 89.99,
    discountPrice: 79.99,
  },
  {
    id: 9,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 1",
    description: "Description 1",
    price: 29.99,
  },
  {
    id: 10,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 2",
    description: "Description 2",
    price: 49.99,
    discountPrice: 39.99,
  },
  {
    id: 11,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 3",
    description: "Description 3",
    price: 19.99,
  },
  {
    id: 12,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 4",
    description: "Description 4",
    price: 89.99,
    discountPrice: 79.99,
  },
  {
    id: 13,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 1",
    description: "Description 1",
    price: 29.99,
  },
  {
    id: 14,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 2",
    description: "Description 2",
    price: 49.99,
    discountPrice: 39.99,
  },
  {
    id: 15,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 3",
    description: "Description 3",
    price: 19.99,
  },
  {
    id: 16,
    image: "http://localhost:3000/cadeira.png",
    title: "Product 4",
    description: "Description 4",
    price: 89.99,
    discountPrice: 79.99,
  },
];

export default mockProducts;
